# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20160102_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='BillModel',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='PaymentMethod',
            new_name='PaymentMethodModel',
        ),
    ]
