# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20160102_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('O', 'Outcome')], default='O', max_length=1),
        ),
    ]
