# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20160102_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iomodel',
            old_name='spent',
            new_name='registered',
        ),
    ]
