# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20160102_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(unique=True)),
                ('end_date', models.DateTimeField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['start_date'],
                'verbose_name': 'billing cycle',
                'verbose_name_plural': 'billing cycles',
            },
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethodmodel',
            options={'ordering': ['name'], 'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
    ]
