# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20160109_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcyclemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billingcyclemodel',
            name='start_date',
            field=models.DateField(unique=True),
        ),
    ]
