# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_auto_20160109_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingCycleModel',
            new_name='BillingModel',
        ),
        migrations.AlterModelOptions(
            name='billingmodel',
            options={'ordering': ['start_date'], 'verbose_name': 'billing', 'verbose_name_plural': 'billings'},
        ),
    ]
