# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20160109_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingModel',
            new_name='BillingCycleModel',
        ),
        migrations.AlterModelOptions(
            name='billingcyclemodel',
            options={'ordering': ['start_date'], 'verbose_name': 'billing cycle', 'verbose_name_plural': 'billing cycles'},
        ),
    ]
