# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_auto_20160110_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethodmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
